// Common Material-UI icon mocks for testing
import React from 'react';

export const Add = () => React.createElement('span', { 'data-testid': 'add-icon' }, '+');
export const Remove = () => React.createElement('span', { 'data-testid': 'remove-icon' }, '-');
export const Edit = () => React.createElement('span', { 'data-testid': 'edit-icon' }, '✏️');
export const Delete = () => React.createElement('span', { 'data-testid': 'delete-icon' }, '🗑️');
export const Search = () => React.createElement('span', { 'data-testid': 'search-icon' }, '🔍');
export const Clear = () => React.createElement('span', { 'data-testid': 'clear-icon' }, '✖');
export const Close = () => React.createElement('span', { 'data-testid': 'close-icon' }, '✖');
export const Menu = () => React.createElement('span', { 'data-testid': 'menu-icon' }, '☰');
export const MenuBook = () => React.createElement('span', { 'data-testid': 'menu-book-icon' }, '📚');
export const ExpandMore = () => React.createElement('span', { 'data-testid': 'expand-more-icon' }, '▼');
export const FilterList = () => React.createElement('span', { 'data-testid': 'filter-icon' }, '⚙️');
export const QrCodeScanner = () => React.createElement('span', { 'data-testid': 'qr-scanner-icon' }, '📱');
export const CameraAlt = () => React.createElement('span', { 'data-testid': 'camera-icon' }, '📷');
export const FlipCameraAndroid = () => React.createElement('span', { 'data-testid': 'flip-camera-icon' }, '🔄');
export const Settings = () => React.createElement('span', { 'data-testid': 'settings-icon' }, '⚙️');
export const Person = () => React.createElement('span', { 'data-testid': 'person-icon' }, '👤');
export const Book = () => React.createElement('span', { 'data-testid': 'book-icon' }, '📖');
export const Home = () => React.createElement('span', { 'data-testid': 'home-icon' }, '🏠');
export const Category = () => React.createElement('span', { 'data-testid': 'category-icon' }, '📂');
export const Star = () => React.createElement('span', { 'data-testid': 'star-icon' }, '⭐');
export const StarBorder = () => React.createElement('span', { 'data-testid': 'star-border-icon' }, '☆');
export const Favorite = () => React.createElement('span', { 'data-testid': 'favorite-icon' }, '❤️');
export const FavoriteBorder = () => React.createElement('span', { 'data-testid': 'favorite-border-icon' }, '🤍');
export const Share = () => React.createElement('span', { 'data-testid': 'share-icon' }, '📤');
export const Download = () => React.createElement('span', { 'data-testid': 'download-icon' }, '📥');
export const Upload = () => React.createElement('span', { 'data-testid': 'upload-icon' }, '📤');
export const Save = () => React.createElement('span', { 'data-testid': 'save-icon' }, '💾');
export const Cancel = () => React.createElement('span', { 'data-testid': 'cancel-icon' }, '❌');
export const Check = () => React.createElement('span', { 'data-testid': 'check-icon' }, '✅');
export const Warning = () => React.createElement('span', { 'data-testid': 'warning-icon' }, '⚠️');
export const Error = () => React.createElement('span', { 'data-testid': 'error-icon' }, '❌');
export const Info = () => React.createElement('span', { 'data-testid': 'info-icon' }, 'ℹ️');
export const Visibility = () => React.createElement('span', { 'data-testid': 'visibility-icon' }, '👁️');
export const VisibilityOff = () => React.createElement('span', { 'data-testid': 'visibility-off-icon' }, '🙈');
export const ArrowBack = () => React.createElement('span', { 'data-testid': 'arrow-back-icon' }, '←');
export const ArrowForward = () => React.createElement('span', { 'data-testid': 'arrow-forward-icon' }, '→');
export const MoreVert = () => React.createElement('span', { 'data-testid': 'more-vert-icon' }, '⋮');
export const MoreHoriz = () => React.createElement('span', { 'data-testid': 'more-horiz-icon' }, '⋯');