import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst, NetworkFirst } from 'workbox-strategies';

interface WorkboxManifestEntry {
  url: string;
  revision?: string | null;
}

interface SyncEventLike extends Event {
  readonly tag: string;
  waitUntil(promise: Promise<unknown>): void;
}

interface PushMessageDataLike {
  text(): string;
}

interface PushEventLike extends Event {
  readonly data?: PushMessageDataLike | null;
  waitUntil(promise: Promise<unknown>): void;
}

interface NotificationWithData {
  close(): void;
  readonly data?: {
    url?: string;
  };
}

interface NotificationClickEventLike extends Event {
  readonly notification: NotificationWithData;
  waitUntil(promise: Promise<unknown>): void;
}

interface ServiceWorkerScope {
  __WB_MANIFEST: Array<WorkboxManifestEntry | string>;
  skipWaiting(): Promise<void>;
  registration: {
    showNotification(title: string, options?: NotificationOptions): Promise<void>;
  };
  clients: {
    openWindow(url: string): Promise<unknown>;
  };
  addEventListener(type: 'message', listener: (event: MessageEvent<{ type?: string }>) => void): void;
  addEventListener(type: 'sync', listener: (event: SyncEventLike) => void): void;
  addEventListener(type: 'push', listener: (event: PushEventLike) => void): void;
  addEventListener(
    type: 'notificationclick',
    listener: (event: NotificationClickEventLike) => void
  ): void;
}

// `webworker` lib types are not enabled in the app tsconfig, so keep the SW surface local.
const serviceWorker = globalThis as unknown as ServiceWorkerScope;

clientsClaim();

// Precache all of the assets generated by your build process.
precacheAndRoute(serviceWorker.__WB_MANIFEST);

// Set up App Shell-style routing
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  ({ request, url }: { request: Request; url: URL }) => {
    if (request.mode !== 'navigate') {
      return false;
    }
    if (url.pathname.startsWith('/_')) {
      return false;
    }
    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    }
    return true;
  },
  createHandlerBoundToURL('/index.html')
);

// Cache API responses
const apiOrigin =
  import.meta.env.VITE_API_ORIGIN ||
  import.meta.env.VITE_API_URL ||
  (import.meta.env.VITE_API_BASE_URL ? new URL(import.meta.env.VITE_API_BASE_URL).origin : '');

registerRoute(
  ({ url }) => Boolean(apiOrigin) && url.origin === apiOrigin,
  new NetworkFirst({
    cacheName: 'api-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 24, // 24 hours
      }),
    ],
  })
);

// Cache images
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);

// Cache web fonts
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com' ||
               url.origin === 'https://fonts.gstatic.com',
  new StaleWhileRevalidate({
    cacheName: 'google-fonts',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 30,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
      }),
    ],
  })
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
serviceWorker.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    serviceWorker.skipWaiting();
  }
});

// Background sync for offline actions
serviceWorker.addEventListener('sync', (event) => {
  if (event.tag === 'background-sync') {
    event.waitUntil(doBackgroundSync());
  }
});

async function doBackgroundSync() {
  // Handle queued offline actions
  // This will be implemented when we add offline functionality
}

// Push notifications (for future implementation)
serviceWorker.addEventListener('push', (event) => {
  const options = {
    body: event.data?.text() || 'New notification',
    icon: '/logo192.png',
    badge: '/logo192.png',
    data: {
      url: '/',
    },
  };

  event.waitUntil(
    serviceWorker.registration.showNotification('My Many Books', options)
  );
});

serviceWorker.addEventListener('notificationclick', (event) => {
  event.notification.close();

  event.waitUntil(
    serviceWorker.clients.openWindow(event.notification.data?.url || '/')
  );
});
