# ================================================================
# serverless.yml - Serverless Framework Configuration
# ================================================================

service: my-many-books-api

frameworkVersion: '>=3.0.0'

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  memorySize: 512
  timeout: 30
  
  # Environment variables
  environment:
    NODE_ENV: ${self:provider.stage}
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT, '5432'}
    DB_NAME: ${env:DB_NAME}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_SSL: ${env:DB_SSL, 'true'}
    API_VERSION: ${env:API_VERSION, '1.0.0'}
    LOG_LEVEL: ${env:LOG_LEVEL, 'info'}
    
    # Security settings
    API_KEYS_ENABLED: ${env:API_KEYS_ENABLED, 'false'}
    COGNITO_ENABLED: ${env:COGNITO_ENABLED, 'false'}
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID, ''}
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID, ''}
    
    # External service settings
    OPEN_LIBRARY_BASE_URL: ${env:OPEN_LIBRARY_BASE_URL, 'https://openlibrary.org'}
    GOOGLE_BOOKS_API_KEY: ${env:GOOGLE_BOOKS_API_KEY, ''}
    GOOGLE_BOOKS_BASE_URL: ${env:GOOGLE_BOOKS_BASE_URL, 'https://www.googleapis.com/books/v1'}
    
    # Performance settings
    CACHE_TTL: ${env:CACHE_TTL, '3600'}
    REQUEST_TIMEOUT: ${env:REQUEST_TIMEOUT, '10000'}
    MAX_RETRIES: ${env:MAX_RETRIES, '3'}

  # API Gateway configuration
  apiGateway:
    restApiId: !Ref ApiGatewayRestApi
    restApiRootResourceId: !GetAtt ApiGatewayRestApi.RootResourceId
    description: My Many Books API - Personal library management system
    
    # Request/response logging
    accessLogging: true
    executionLogging: true
    fullExecutionData: true
    
    # Request validation
    request:
      schemas:
        book-request-model:
          name: BookRequest
          description: Request model for book operations
          schema: ${file(config/schemas/book-request.json)}
        author-request-model:
          name: AuthorRequest  
          description: Request model for author operations
          schema: ${file(config/schemas/author-request.json)}
        category-request-model:
          name: CategoryRequest
          description: Request model for category operations
          schema: ${file(config/schemas/category-request.json)}
    
    # API documentation
    documentation: ${file(config/api-gateway.yml):apiGateway.documentation}
    
    # Usage plans
    usagePlan:
      - basic:
          quota:
            limit: 10000
            offset: 0
            period: MONTH
          throttle:
            burstLimit: 100
            rateLimit: 50
          apiStages:
            - api: !Ref ApiGatewayRestApi
              stage: ${self:provider.stage}
      - premium:
          quota:
            limit: 100000
            offset: 0
            period: MONTH
          throttle:
            burstLimit: 500
            rateLimit: 200
          apiStages:
            - api: !Ref ApiGatewayRestApi
              stage: ${self:provider.stage}

  # IAM permissions
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: 'arn:aws:logs:*:*:*'
        - Effect: Allow
          Action:
            - apigateway:GET
            - apigateway:POST
            - apigateway:PUT
            - apigateway:DELETE
          Resource: 'arn:aws:apigateway:*::/restapis/*'
        - Effect: Allow
          Action:
            - execute-api:Invoke
          Resource: 'arn:aws:execute-api:*:*:*'

  # Tags for resource management  
  tags:
    Project: my-many-books
    Environment: ${self:provider.stage}
    Service: api
    CreatedBy: serverless

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node18
    external:
      - pg-native
    exclude:
      - aws-sdk
  serverless-offline:
    httpPort: 3000
    port: 3000

functions:
  # Single function deployment (recommended for API Gateway)
  api:
    handler: src/handlers/router.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
      - http:
          path: /
          method: ANY
          cors: true

  # Separate function deployments (alternative approach)
  # Uncomment below if you prefer separate Lambda functions per resource

  # books-create:
  #   handler: src/handlers/books.createBook
  #   events:
  #     - http:
  #         path: /books
  #         method: post
  #         cors: true

  # books-get:
  #   handler: src/handlers/books.getBook
  #   events:
  #     - http:
  #         path: /books/{id}
  #         method: get
  #         cors: true

  # books-update:
  #   handler: src/handlers/books.updateBook
  #   events:
  #     - http:
  #         path: /books/{id}
  #         method: put
  #         cors: true

  # books-delete:
  #   handler: src/handlers/books.deleteBook
  #   events:
  #     - http:
  #         path: /books/{id}
  #         method: delete
  #         cors: true

  # books-list:
  #   handler: src/handlers/books.listBooks
  #   events:
  #     - http:
  #         path: /books
  #         method: get
  #         cors: true

  # books-search-isbn:
  #   handler: src/handlers/books.searchBooksByIsbn
  #   events:
  #     - http:
  #         path: /books/search/isbn
  #         method: get
  #         cors: true

  # books-import-isbn:
  #   handler: src/handlers/books.importBookFromIsbn
  #   events:
  #     - http:
  #         path: /books/import/isbn
  #         method: post
  #         cors: true

  # authors-create:
  #   handler: src/handlers/authors.createAuthor
  #   events:
  #     - http:
  #         path: /authors
  #         method: post
  #         cors: true

  # authors-get:
  #   handler: src/handlers/authors.getAuthor
  #   events:
  #     - http:
  #         path: /authors/{id}
  #         method: get
  #         cors: true

  # authors-update:
  #   handler: src/handlers/authors.updateAuthor
  #   events:
  #     - http:
  #         path: /authors/{id}
  #         method: put
  #         cors: true

  # authors-delete:
  #   handler: src/handlers/authors.deleteAuthor
  #   events:
  #     - http:
  #         path: /authors/{id}
  #         method: delete
  #         cors: true

  # authors-list:
  #   handler: src/handlers/authors.listAuthors
  #   events:
  #     - http:
  #         path: /authors
  #         method: get
  #         cors: true

  # authors-books:
  #   handler: src/handlers/authors.getAuthorBooks
  #   events:
  #     - http:
  #         path: /authors/{id}/books
  #         method: get
  #         cors: true

  # Health check
  health:
    handler: src/handlers/health.healthCheck
    events:
      - http:
          path: /health
          method: get
          cors: true

  readiness:
    handler: src/handlers/health.readinessCheck
    events:
      - http:
          path: /readiness
          method: get
          cors: true

resources:
  Resources:
    # API Gateway CORS configuration
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'RestApiApigEvent'

    GatewayResponseDefault5XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: 'RestApiApigEvent'