AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Cognito resources for My Many Books application'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

  ServiceName:
    Type: String
    Default: my-many-books-api
    Description: Service name

Resources:
  # Cognito User Pool
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${ServiceName}-user-pool-${Environment}'
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_LINK
        EmailSubject: "Verify your My Many Books account"
        EmailMessage: "Please click the link below to verify your email address for My Many Books: {####}"
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      UserAttributeUpdateSettings:
        AttributesRequireVerificationBeforeUpdate:
          - email
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      UserPoolTags:
        Project: my-many-books
        Environment: !Ref Environment
        Service: auth
        CreatedBy: cloudformation

  # Cognito User Pool Client
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub '${ServiceName}-client-${Environment}'
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        - http://localhost:3000
        - https://localhost:3000
        - !Sub 'https://${ServiceName}-web-${Environment}.s3-website-${AWS::Region}.amazonaws.com'
      LogoutURLs:
        - http://localhost:3000
        - https://localhost:3000
        - !Sub 'https://${ServiceName}-web-${Environment}.s3-website-${AWS::Region}.amazonaws.com'
      AccessTokenValidity: 24
      IdTokenValidity: 24
      RefreshTokenValidity: 30
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH

  # Cognito User Pool Domain
  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub '${ServiceName}-auth-${Environment}'
      UserPoolId: !Ref CognitoUserPool

  # Cognito Identity Pool
  CognitoIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: !Sub '${ServiceName}-identity-pool-${Environment}'
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref CognitoUserPoolClient
          ProviderName: !GetAtt CognitoUserPool.ProviderName
          ServerSideTokenCheck: false

  # IAM Role for authenticated users
  CognitoAuthRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ServiceName}-authenticated-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud: !Ref CognitoIdentityPool
              ForAnyValue:StringLike:
                cognito-identity.amazonaws.com:amr: authenticated
      Policies:
        - PolicyName: CognitoAuthenticatedPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - mobileanalytics:PutEvents
                  - cognito-sync:*
                  - cognito-identity:*
                Resource: '*'
      Tags:
        - Key: Project
          Value: my-many-books
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: auth
        - Key: CreatedBy
          Value: cloudformation

  # Attach role to identity pool
  CognitoIdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref CognitoIdentityPool
      Roles:
        authenticated: !GetAtt CognitoAuthRole.Arn

# CloudFormation Outputs
Outputs:
  CognitoUserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref CognitoUserPool
    Export:
      Name: !Sub '${ServiceName}-${Environment}-CognitoUserPoolId'

  CognitoUserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref CognitoUserPoolClient
    Export:
      Name: !Sub '${ServiceName}-${Environment}-CognitoUserPoolClientId'

  CognitoIdentityPoolId:
    Description: Cognito Identity Pool ID
    Value: !Ref CognitoIdentityPool
    Export:
      Name: !Sub '${ServiceName}-${Environment}-CognitoIdentityPoolId'

  CognitoUserPoolArn:
    Description: Cognito User Pool ARN
    Value: !GetAtt CognitoUserPool.Arn
    Export:
      Name: !Sub '${ServiceName}-${Environment}-CognitoUserPoolArn'

  CognitoUserPoolDomain:
    Description: Cognito User Pool Domain
    Value: !Ref CognitoUserPoolDomain
    Export:
      Name: !Sub '${ServiceName}-${Environment}-CognitoUserPoolDomain'

  AwsRegion:
    Description: AWS Region
    Value: !Ref AWS::Region
    Export:
      Name: !Sub '${ServiceName}-${Environment}-AwsRegion'
