/**
 * Standardized error codes for API responses
 * Machine-readable codes that clients can translate to localized messages
 */

export const ERROR_CODES = {
  // Authentication (1xxx)
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_HEADER_INVALID: 'AUTH_HEADER_INVALID',
  AUTH_FAILED: 'AUTH_FAILED',

  // Authorization (2xxx)
  FORBIDDEN: 'FORBIDDEN',
  ADMIN_REQUIRED: 'ADMIN_REQUIRED',
  ROLE_REQUIRED: 'ROLE_REQUIRED',
  ACCOUNT_DEACTIVATED: 'ACCOUNT_DEACTIVATED',

  // API Key (3xxx)
  API_KEY_MISSING: 'API_KEY_MISSING',
  API_KEY_INVALID: 'API_KEY_INVALID',
  API_KEY_TIER_NOT_FOUND: 'API_KEY_TIER_NOT_FOUND',

  // Rate Limiting (4xxx)
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
  USAGE_LIMIT_EXCEEDED: 'USAGE_LIMIT_EXCEEDED',

  // Validation (5xxx)
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVALID_REQUEST_BODY: 'INVALID_REQUEST_BODY',

  // Resources (6xxx)
  NOT_FOUND: 'NOT_FOUND',

  // Server (9xxx)
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
